name: qmllint reviewer
description: Creates review comments from qmlint json files
author: Amarula Solutions

inputs:
  jsondir:
    description: Absolute Path to qmllint json files
    default: ''
    type: string
  repodir:
    description: Absolute Path to local repo
    default: ${{ github.workspace }}
    type: string

runs:
  using: "composite"
  steps:

    - uses: robinraju/release-downloader@v1.10
      id: download
      with:
        latest: true
        extract: true
        repository: "EddyTheCo/qmllint-action"
        fileName: "*Linux*.tar.gz"

    - name: Run
      shell: 'bash'
      run: |
        echo ${{ github.workspace }}/${{ fromJson(steps.download.outputs.downloaded_files)[0] }}
        export LD_LIBRARY_PATH=${{ github.workspace }}/${{ fromJson(steps.download.outputs.downloaded_files)[0] }}/lib
        ls -R ${{ github.workspace }}/${{ fromJson(steps.download.outputs.downloaded_files)[0] }}
        ${{ github.workspace }}/${{ fromJson(steps.download.outputs.downloaded_files)[0] }}/bin/qmllC ${{ inputs.jsondir }}  ${{ inputs.repodir }} repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/reviews ${{ github.token }}
