name: qmllint reviewer
description: Creates review comments from qmlint json files
author: Amarula Solutions

inputs:
  jsondir:
    description: Absolute Path to qmllint json files
    default: ''
    type: string
  repodir:
    description: Absolute Path to local repo
    default: ${{ github.workspace }}
    type: string
  pr_number:
    default: ''
    type: string

runs:
  using: "composite"
  steps:

    - uses: robinraju/release-downloader@v1.10
      id: download
      with:
        latest: true
        extract: true
        repository: "EddyTheCo/qmllint-action"
        fileName: "*Linux*.tar.gz"

    - name: Run
      shell: 'bash'
      run: |
        echo ${{ github.workspace }}/${{ fromJson(steps.download.outputs.downloaded_files)[0] }}
        export DPATH=$(echo ${{ fromJson(steps.download.outputs.downloaded_files)[0] }} | sed 's/\.tar\.gz//g')
        echo $DPATH
        export LD_LIBRARY_PATH=$DPATH/lib
        $DPATH/bin/qmllintBot ${{ inputs.jsondir }}  ${{ inputs.repodir }} ${{ github.repository }} ${{ inputs.pr_number }} ${{ github.token }}
